default:
	g++ -O3 -flto -DNDEBUG -march=native -std=c++17 -Wall main.cpp -o out

debug:
	g++ -O3 -flto -march=native -std=c++17 -g3 -fno-omit-frame-pointer -Wall main.cpp -o out
	
clean:
	rm *.o *.exe


